name: "Setup environment"
description: "Checkout repo, setup Python and dependencies"
inputs:
  python-version:
    required: true
  setup-name:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - uses: ./.github/actions/set-pip-path-and-cache-key

    - name: pip-install (-e) PySDM and PySDM-examples
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[CI_version_pins]
        python -We -c "import PySDM"  # sanity check
        python -m pip install -e .[tests,CI_version_pins] -e ./examples[CI_version_pins]
        python -We -c "import PySDM, PySDM_examples"
        python -m pip install -r tests/devops_tests/requirements.txt
      shell: bash

    - uses: actions/cache/save@v4
      with:
        path: ${{ env.pip_user_site }}
        key: ${{ inputs.setup-name }}-${{ env.toml_ci_md5 }}
