name: "Setup environment"
description: "Checkout repo, setup Python and dependencies"
inputs:
  python-version:
    required: true
  setup-name:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - uses: ./.github/actions/set-pip-path-and-cache-key

    - name: Setup environment
      if: ( !startsWith(inputs.setup-name, 'examples') )
      run: |
        python -m pip install -e .[tests,CI_version_pins]
        python -We -c "import PySDM"
      shell: bash

    - name: Install examples if needed
      if: ( startsWith(inputs.setup-name, 'examples') )
      run: |
        python -m pip install -e .[tessts,CI_version_pins] -e ./examples[CI_version_pins]
        python -We -c "import PySDM, PySDM_examples"
      shell: bash

    - name: Install devops-tests requirements
      run: |
        python -m pip install -r tests/devops_tests/requirements.txt
      shell: bash

    - uses: actions/cache/save@v4
      with:
        path: ${{ env.pip_user_site }}
        key: ${{ inputs.setup-name }}-${{ env.toml_ci_md5 }}
