name: "Setup environment"
description: "Checkout repo, setup Python and dependencies"
inputs:
  python-version:
    required: true
  platform:
    required: true
  setup-name:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - uses: ./.github/actions/set-pip-path-and-cache-key

    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pip_user_site }}
        key: ${{ inputs.setup-name }}-${{ inputs.platform}}-${{ inputs.python-version }}-${{ env.toml_ci_md5 }}
        lookup-only: true

    - name: Setup environment
      run: |
        # python -m pip uninstall -y jupyterlab-server # https://github.com/pypa/pip/issues/6275
        python -m pip install -e .
        # sanity check if we do not depend on something from tests extras
        python -We -c "import PySDM"
        python -m pip install pytest-timeout
        python -m pip install -r tests/devops_tests/requirements.txt
      shell: bash

    - name: Install examples and PyPartMC if needed
      if: StartsWith(inputs.setup-name, 'examples')
      run: |
        python -m pip install -e ./examples
        python -m pip install PyPartMC
      shell: bash
