name: "Setup environment"
description: "Checkout repo, setup Python and dependencies"
inputs:
  python-version:
    required: true
  cache-key-prefix:
    required: true
  commands:
    required: true
  hash-input-files:
    required: true
    description: "Space-separated list of files to hash for cache key"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4.1.6
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v5.0.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Calculate pip path and cache key
      run: |
        echo "pip_user_site=$(python -c "import sysconfig; print(sysconfig.get_path('purelib'))")" >> $GITHUB_ENV
        hash_input_files="${{ inputs.hash-input-files }}"
        echo "toml_ci_md5=$(cat $hash_input_files | python -c 'import hashlib; print(hashlib.md5(open(0, """rb""").read()).hexdigest())')" >> $GITHUB_ENV
      shell: bash

    - uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.pip_user_site }}
        key: ${{ inputs.cache-key-prefix }}-${{ inputs.python-version }}-${{ env.toml_ci_md5 }}
        lookup-only: true

    - name: Setup environment
      if: inputs.commands != ''
      run: ${{ inputs.commands }}
      shell: bash

